version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: back.dockerfile
    image: "back_node"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ./frontend
      dockerfile: front.dockerfile
    image: "front_react"
    ports:
      - "3000:3000"